### ISSUE TITLE
Highlight Text in editor

### ISSUE THREAD

**Issue by RoraxHan** [tinymce/tinymce-vue#104]
I want to highlight some text.
For example, If I have keyword like 'dog' and editor has 5 words of dog, then I want to highlight all of words 'dog' in editor.

But When I get html string from editor, I don't want any changed html source for highlight.
highlight the keyword is only for visualization during editing content.

Highlight needs to be updated in real time during edit.
(I've already purchased 'Pro' Plan for tinymce. )

Please help me for this.

**Comment by SimonFc** [comment]
This sounds like a feature which TinyMCE doesn't have so it'll be something you'll need to implement by yourself. Feel free to open up a feature request in the TinyMCE repository though! Some ideas for how to go about it if I were to do it:

I would create this feature as a plugin and call it "highlighter" or something like that. Read more about the creation of plugins [over here](https://www.tiny.cloud/docs/advanced/creating-a-plugin/)

In this plugin I would listen to a few events, perhaps [NodeChange](https://www.tiny.cloud/docs/advanced/events/#nodechange) or the keypress/paste events etc.
`editor.on('NodeChange', () => { /* Do the highlighting here */ });`

Then comes the tricky part of finding any matches of what you're looking for and applying the formatting you desire to have in the DOM, perhaps with a class and then have css for this class in the [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) option. This can be very difficult due to all the edge cases that exist(words divided by spans etc.) so I'll leave this to you.

Finally, I would look at the [content filtering](https://www.tiny.cloud/docs/configure/content-filtering/) options and apply the appropriate settings so that you filter out the styling you use for highlighting.

(If you only need something very rudimentary I managed to achieve this by utilizing the textpattern plugin: [example](http://fiddle.tinymce.com/0Rgaab). Just type "dog" somewhere)

**Comment by RoraxHan** [comment]
@SimonFc  Thanks for your good example.
But When I change something in the View/Source Code, then all highlight is disappeared.

**Comment by SimonFc** [comment]
Perhaps my example would be better by using a class for highlights like [this](http://fiddle.tinymce.com/8Rgaab). If you want to remove it when running `editor.getContent()` there are probably some [content filtering](https://www.tiny.cloud/docs/configure/content-filtering/) options which you could use to achieve that.

So intercepting setContent and applying highlight is one scenario that you need to cover? To answer your question, yes there's a setContent event. You can use it like this `editor.on('SetContent', (e) => { });`
This approach is closer to my recommendation of making this into a plugin though since depending on your use case there might be a lot of cases to cover :)

**Comment by TomCasano** [comment]
@SimonFc Is there a way to get this highlighting to happen at startup?  If the tinyMCE field is prepopulated with content, it's not highlighting until I put the cursor in the field, immediately after the word or phrase I want to highlight, and press a key

**Comment by TomCasano** [comment]
@SimonFc Additionally, if you then edit the text, to add a space in the middle of the highlighted word, so that it's no longer a match, it doesn't un-highlight it.
