### ISSUE TITLE
Is it possible to catch an event when a comment was posted?

### ISSUE THREAD

**Issue by phuclh** [tinymce/tinymce-vue#105]
When using TinyMCE Comment 2.0 to create a comment in the editor. TinyMCE will generate a code to highlight the text in content, something like that:
`<span class="mce-annotation tox-comment tox-comment--active" data-mce-annotation-uid="1569391788" data-mce-annotation="tinycomments">ing to get it righ</span>`

It means the content is `dirty` and I want to save my new content into the database. But I cannot find any event on comment was created or something like that.

I did try to use `onDirty` event and it worked, but I don't that event will also fire if a user makes a change on content (not create comment). I don't want that because there is too many request to server.

Thank you!

**Comment by SimonFc** [comment]
Judging by your questions I'm assuming you're using callback mode right? So using `tinycomments_create` you know when a comment/conversation is being created, and if I understand you correctly you need a way to know when (after the done callback has been called) the generated annotation has been inserted into the editors content?

I've been looking at it for a little while, including the underlying [Annotations](https://www.tiny.cloud/docs/advanced/annotations/) API to see if there's something you could hook into but I don't think we expose anything for that specifically :thinking: 

What's the use case for listening for that specifically though? I'm guessing you would want to save the content of the editor whenever a change has been made and not just when a conversation has been started. I think the simplest way to do that is to use the [v-model](https://github.com/tinymce/tinymce-vue#v-model) since you're using tinymce-vue. Or maybe just the onChange event.

**Comment by phuclh** [comment]
As I mentioned in the last previous question, I cannot acces `this` in `tinycomments_create` function, so I have to make a global variable of vue instance, something like this:
```
mounted() {
            window.vm = this; // Make global Vue instance to access in tinyMCE comment

            ...
        },
```

And access the `vm` variable in `tinycomments_create` to get the content from v-model
```
tinycomments_create: function (req, done, fail) {
                        vm.$store.dispatch('comment/create', {
                            request: req,
                            articleId: vm.resourceId
                        }).then(res => {
                            done({conversationUid: res.data});

                            console.log(vm.article) // This statment just print my old content, not the content after I add a new comment.
                        });
                    },
```

But whatever I change my  content, `vm.article` only print the old content (It looks like v-model isn't updated).

**Comment by phuclh** [comment]
@SimonFc If I use onChange event, there are too many requests to the server. I only need an event that is triggered when the content changes cause by comment. Do you have any ideas?

Thank you for your great support!

**Comment by SimonFc** [comment]
I'm happy to help! Since there's no API/event for this I think the simplest solution would be to filter on the `Change` event. Perhaps something like this:
```
<template>
  <Editor :init="init" />
</template>

<script>
  export default {
    components: {
      'editor': Editor
    },
    data: function () {
      return {
        lastConversationUid: undefined,
        init: {
          plugins: 'tinycomments',
          tinycomments_create: (req, done, fail) => {
            const uid = 'my-super-random-annotation-id' ;

            // Do async store dispatch
            
            this.lastConversationUid = uid;
            done({ conversationUid: uid });
          },

          /* ... register the other callbacks */

          setup: (editor) => {
            editor.on('Change', (e) => {
              if (
                typeof this.lastConversationUid === 'string' &&
                e.level.content.includes(this.lastConversationUid)
              ) {
                console.log('New conversation has been inserted into the DOM');
                this.lastConversationUid = undefined;
              }
            });
          }
        }
      }
    }
  }
</script>
```
It is a workaround but I don't think we'll add any custom events for this since it's a very specific usecase :thinking:

(I'll close this since it isn't a bug with tinymce-vue which this channel of communication is for but let me know if the example I gave doesn't work!)

**Comment by phuclh** [comment]
You're awesome, thank you so much! That's work :D. I just need to twist the code a bit.

I have 1 more question that I think this is the last one for this plugin :D. Is there any way to show all comments by default. Currently, It shows when I click to a highlighted text. Something like this plugin: https://www.loopindex.com/lance/demo/tmce/

<img width="1330" alt="Screen Shot 2019-09-25 at 12 11 39 PM" src="https://user-images.githubusercontent.com/6707194/65632063-a7328700-df8d-11e9-9f23-d1ea54d4a092.png">

**Comment by SimonFc** [comment]
@phuclh No problem! No unfortunately the current version of Comments doesn't have that future
