### ISSUE TITLE
The API key you have entered is invalid.

### ISSUE THREAD

**Issue by iagosilvamelo** [tinymce/tinymce-vue#108]
Good morning.

I'm uses tiny in a vue project and my editor open but return this message: "The API key you have entered is invalid. Please review your API key here."

My api-key is correct and i verify in my tiny account.

**Info**
1 - In the first render the tiny editor open normaly but when updated started to return the error.
2 - I have more of one editor in my page.
3 - My account is free.

How can i solve?
Thanks for your attention.

**Comment by SimonFc** [comment]
Hi,

When you say that you get the error after updating, do you mean that you re-render the tinymce-vue component? (no page refresh) If so, that's strange. The TinyMCE main script will be only be loaded  once since any subsequent renders will detect that TinyMCE already is in the global scope. There's also a shared state between all tinymce-vue components that ensures that's it's only loaded once in case of parallel (initial) rendering :thinking: 

Can you describe, or perhaps provide a reproduction, of what you mean by "update"? Since it works on initial render it feels like it must be something related to your specific use case

**Comment by iagosilvamelo** [comment]
Good morning SimonFc, thanks for your response.

The api_key it only worked once, then it didn't work anymore. Even when I open the browser with nothing in cookie the error message appears.

The TinyMCE works normally, but the error message always appears with "The API key you have entered is invalid"

**Comment by SimonFc** [comment]
Since you say that it works initially (no error message on first editor load) I would like to know what you are doing different on subsequent renders. Perhaps tinymce-vue actually loads TinyMCE multiple times on subsequent renders (which would be a bug on our side) and the api key just happen to be configured badly for the other editors or something. If possible, a minimal reproduction of your issue would be great so that we can rule that out.

Something you could try is to remove the api-key prop from all of your editor(s) in your templates and load TinyMCE by yourself by making sure this is being run before any editor renders:
```<script src="https://cdn.tiny.cloud/1/insert-your-api-key-here/tinymce/5/tinymce.min.js"></script>```

**Comment by jscasca** [comment]
@iagosilvamelo, just wondering if that last solution worked for you or if you are still having issues with TinyMCE's API keys?

**Comment by vinayk7** [comment]
Same here

**Comment by mochj12** [comment]
how long is  the  TinyMCE's API keys  valid  times  ?
