### ISSUE TITLE
Problem when Tiny Mce component is in a modal. 

### ISSUE THREAD

**Issue by zm576** [tinymce/tinymce-vue#113]
Hello, 

I’m trying to integrate the tiny mce vue component in a Bootsrap modal.  

The first load of Tiny Mce component works fine. Then if I close the modal, it becomes impossible to edit the body of the Tiny Mce component. It is totally blank. 
If I take a look at the Dom, I can see the `<body>` tag of Tiny Mce component is empty. And if I click in the editor my mouse pointer cannot get the focus in the iframe.  

I have tried to implement different solutions to fix that problem but I haven’t found any solutions working.  

Can someone help me to solve that problem ?

**Comment by asika32764** [comment]
See https://github.com/tinymce/tinymce-vue/issues/106

**Comment by SimonFc** [comment]
Ah this actually isn't due to #106 but rather is due to how the iframe will re-render whenever it's detached from the DOM by Vue when you close the dialog. This is a normal iframe behavior but causes problems for TinyMCE. [This](https://codesandbox.io/s/bootstrapvue-tinymce-vue-modal-focusin-kxhvm) is a great example for how to get around this issue.

**Comment by SimonFc** [comment]
Thanks @asika32764 
Closing this, unfortunately I don't think tinymce-vue can provide a work-around to this issue. We'll update the Storybook examples to include a demo of the work-around I mentioned in the discussion over at Bootstrap Vue so as to help people who might encounter it in the future.
