### ISSUE TITLE
Content not editable

### ISSUE THREAD

**Issue by goraSi** [tinymce/tinymce-vue#129]
I'm using Nuxt.js + Vuetify latest version with this plugin. Editor is shown in v-dialog with option `:retain-focus="false"` as per docs from Vuetify. I have a strange situation in some cases that after i open dialog for second time, the tinymce content is not editable. I have inspected DOM and i can see that head and body elements of TinyMCE are empty. I'm also using `v-if `directive to re-render component every time.

Any suggestions why this is happening.

This problem doesn't occur when using Vuetify 2.1.10 and @tinymce/tinymce-vue@3.0.1.

**Comment by goraSi** [comment]
Closing this since i have discovered this is a bug starting from Vuetify 2.2.9.

**Comment by mikewalkerjr** [comment]
I am experiencing the exact same issue using Vuetify 2.2.9 and was curious if you found a workaround while using Vuetify version 2.2.9?

**Comment by goraSi** [comment]
Here is my snippet of v-dialog which includes TinyMCE component:

`<v-dialog v-model="dialogReply" max-width="1024px" persistent :retain-focus="false" eager>`

**Comment by mikewalkerjr** [comment]
Thank you very much, the `eager` prop I overlooked and helped a lot.

**Comment by articleten-andy** [comment]
I still seem to be experiencing this.

I've added the eager prop to my dialog, and the :retain-focus="false".

But every time I close my dialog, and then re-open it, the tinymce instance doesn't re-initialise fully, I can't edit anything, and it won't let me insert templates etc. It's as if the underlying textarea wasn't there when it initialised.

Once I close my dialog, it's removed via a v-if, does that make a difference.

Is there anything else to try?

**Comment by AndersonGuerra** [comment]
@articleten-andy could you explain a bit more? I'm facing the same problem, but I did not manage to solve it

**Comment by articleten-andy** [comment]
> @articleten-andy could you explain a bit more? I'm facing the same problem, but I did not manage to solve it

Sorry, I just checked back over my projects, the ones where I use tinymce-vue, and all the places where i've used the eager prop and :retain-focus="false", I can't see anywhere where i've used nextTick to delay anything, so it was either some scenario which was very specific and I can't find it, or it's perhaps fixed with a newer version number and i've since removed the code.

Looking at the code I can't even see what I would have been delaying with nextTick, as there isn't really anything being loaded other than the config to be passed as a prop.
