### ISSUE TITLE
v-model variable cannot be updated when I call setNode method

### ISSUE THREAD

**Issue by yanshuok** [tinymce/tinymce-vue#145]
I used tinymce-vue in my project, and use v-model to bind a variable. 
Then I used tinymce.DOM.create() to create a element. Finnaly, I the element into the editor by tinymce.activeEditor.selection.setNode(). 
I expected the value bound with the editor by v-model to be updated but It wasn't until I did something with the GUI. I also need to delete twice to eliminate the content I inserted.
tinyMCE: 5.2.1
tinymce-vue: 3.2.0
OS: windows 10 1809
browser: chrome 77.0.3865.90
I do not use other version of tinyMCE so I dont know if it happens in other versions.

**Comment by jscasca** [comment]
Hi @yanshuok 

the v-model value will update, by default, on the TinyMCE editor `change keyup undo redo` events. Doing a `selection.setNode()` will not trigger any of those events so the v-model value will not be updated. In your code you can fire a `change` event so that it propagates through the wrapper or you can change the default events bound to the v-model by using the modelEvents property.

Let me know if this helps

**Comment by yanshuok** [comment]
But how can I fire a change event?

**Comment by jscasca** [comment]
@yanshuok 

If you already have the instance of the editor you can call the `fire` function. For example: `tinymce.activeEditor.fire('change')`

**Comment by yanshuok** [comment]
Thank you very much! Your solution was very helpful.
