### ISSUE TITLE
Fullscreen plugin not showing

### ISSUE THREAD

**Issue by Mert75** [tinymce/tinymce-vue#160]
**What is the current behavior?**
Non premium plugin of fullscreen is not working / showing

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/9y95z5m40y?fontsize=14) or similar.**
<editor
      api-key="key"
      class="myreply w-100 mt-4"
      :init="{
        selector: '.myreply',
        height: 100,
        inline: true,
        menubar: false,
        statusbar: false,
        placeholder: 'Type here...',
        plugins: [
          'autolink autosave save directionality fullscreen template lists emoticons',
        ],
        toolbar:
          'bold italic underline strikethrough numlist bullist emoticons '
      }"
    ></editor>

**What is the expected behavior?**
Plugin should be working

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-vue?**

TinyMCE v5 on Chrome 84, haven't tried on other versions

**Comment by jscasca** [comment]
Hi @Mert75 

Can you attach a screenshot of what you are seeing? I tried on a sandbox and it seems to be working properly. Is the following sandbox working for you: [full sccreen example](https://codesandbox.io/s/tinymcevue-forked-te66z?file=/src/App.vue) ?

**Comment by Mert75** [comment]
Hi @jscasca , thanks for your reply

However it seems like I forgot to specify that it occurs on `inline` mode. The sandbox you sent is working, just not when inline, see [codepen](https://codesandbox.io/s/tinymcevue-forked-lkm9y).

**Comment by jscasca** [comment]
Unfortunately, full-screen is currently not supported in inline mode. Initially, it was not supported in TinyMCE since the user has enough control over the area in which the editor in mounted to implement the functionality themselves. However, since using the Vue wrapper doesn't give that ability to the user this is currently a limitation on our part.

We are researching an implementation using the shadow DOM that would allow this functionality but in the meantime it will not be supported. Sad to say, we don't have a time estimate on when that will be achieved
