### ISSUE TITLE
Image upload on iOS

### ISSUE THREAD

**Issue by tiagocostafdm** [tinymce/tinymce-vue#214]
Users can't select images to upload, when click the image upload icon, the file picker doesn't show up, nothing happens.

This happens when using the editor on an iPad.

The users should be able pick an image and upload it.

Using version 3.2.7 or below on safari on iPad.

**Comment by jscasca** [comment]
Hi @tiagocostafdm 

Can you provide your current configuration? I couldn't replicate this behaviour with a default configuration. What version of TinyMCE are you using? Have you tried a different TinyMCE version?

![IMG_0007](https://user-images.githubusercontent.com/6062777/104549716-1ea69100-567f-11eb-9cad-d1f58fc3be0d.PNG)

**Comment by tiagocostafdm** [comment]
Hi @jscasca 
We are using version 1.0.8, but I've tried 2.x.x and 3.x.x and but those also didn't work, I've tried a 4.x.x version but is not compatible with our project configs, the project won't run.

**Comment by jscasca** [comment]
Hi @tiagocostafdm 

You mean the wrapper version? You can configure what version of the TinyMCE editor (not the wrapper) you use by [choosing a cloud channel](https://www.tiny.cloud/docs/integrations/vue/#cloud-channel), or by [using a script source](https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src). Maybe try with `5.5` in case the issue is a recent regression?

**Comment by tiagocostafdm** [comment]
@jscasca I was updating the wrapper version, didn't know there was a script source as well and after updating this script, that was on version 4.9.6, to version 5.6.2 ( latest ) it worked ok, thank you.
