### ISSUE TITLE
programmatically preload or initialize tinymce

### ISSUE THREAD

**Issue by thomas-topway-it** [tinymce/tinymce-vue#219]
I'm trying to use tinymce in a vuejs dialog (with a textarea inside) and the issue is that to load the first time it takes about 1 second, which causes a poor user experience.

Once I close the dialog and I reopen it, it loads instantly and that's fine.
I have tried to include all the required files in the html itself, but they get mistakenly reloaded as the following ticket

https://github.com/tinymce/tinymce-vue/issues/182

However, I don't think that just a preload of the files solves the issue, and that the component should be able to programmatically be initialized through some external function.

Do you have any hint or workaround to solve the issue ?

thanks
(Thomas)

**Comment by jscasca** [comment]
Hi Thomas, Unfortunately, we currently don't have a way of preloading the component. The vue wrapper just initialises the editor but it is TinyMCE that needs to initialise on the iFrame and bind all the necessary events. Due to the nature of the iFrame it can't be loaded off screen and then presented to the users.

At the time, I don't have an answer for this
