### ISSUE TITLE
Country Flags not render on Windows 10

### ISSUE THREAD

**Issue by paulocastellano** [tinymce/tinymce-vue#237]
Country flags are not being rendered in Windows 10.

I also tested it on Linux and Mac OS X and it is working perfectly.

Vue: 2
TinyMCE-VUE: version 3.28

Video:
![Peek 2021-04-14 22-13](https://user-images.githubusercontent.com/265964/114799853-fd813980-9d6e-11eb-82d7-77939bd17592.gif)

**Comment by jscasca** [comment]
Hi @paulocastellano 

Unfortunately, this is not related to the vue-wrapper implementation or the TinyMCE editor, as far as I know, but the reason is simply that windows 10 ships without flags emojis. You would need a custom emoji font that includes the flags that you want to use. The content will display properly when viewed in a different system.

There is not much we can with the vue-wrapper to work around this issue so I'm going to close this issue.
