### ISSUE TITLE
Add spellchecker to editor

### ISSUE THREAD

**Issue by CesarUCIGIT** [tinymce/tinymce-vue#253]
I think it may be really good for this component to support spellcheck. I tried using the official plugin https://www.tiny.cloud/docs/plugins/opensource/spellchecker/ but after following the steps I couldn't make it work and I'm pretty sure it's because it is not compatible with this component. I also tried using this library getting the same results https://tinymcespellcheck.com/

**Comment by jscasca** [comment]
Hi @CesarUCIGIT 

The spellchecker plugin has been deprecated since TinyMCE 5.4. You can find out more here: https://www.tiny.cloud/docs/plugins/opensource/spellchecker/ or heading to the original [TinyMCE repo](https://github.com/tinymce/tinymce).

The Vue component does support spellcheck. Here is a sandbox of the callback working properly without a server:  https://codesandbox.io/s/tinymcevue-forked-5obgi?file=/src/App.vue

This repo is only for issue related to the Vue wrapper so more questions regarding your implementation will probably be best answered in the [TinyMCE repo](https://github.com/tinymce/tinymce)
