### ISSUE TITLE
这东西太难玩了，虽然能用

### ISSUE THREAD

**Issue by mkinit** [tinymce/tinymce-vue#261]
这东西太难玩了。
虽然能用，但是会覆盖我的样式；
虽然能用，但是控制台会报错，这不能忍。
我只是想用个编辑器而已啊……
再见。无力折腾！

**Comment by tiny-james** [comment]
Thanks for the poetry!

I am uncertain if it is translation errors but I don't have a clear understanding of what is going wrong from your description. Can you give us an example of the editor configuration you are using? You also mentioned console errors, can you please include them with your bug report?

--------

谢谢你的诗！

我不确定这是否是翻译错误，但我不清楚您的描述中出了什么问题。 你能给我们一个你正在使用的编辑器配置的例子吗？ 您还提到了控制台错误，能否将它们包含在您的错误报告中？

**Comment by mkinit** [comment]
> Thanks for the poetry!
> 
> I am uncertain if it is translation errors but I don't have a clear understanding of what is going wrong from your description. Can you give us an example of the editor configuration you are using? You also mentioned console errors, can you please include them with your bug report?
> 
> 谢谢你的诗！
> 
> 我不确定这是否是翻译错误，但我不清楚您的描述中出了什么问题。 你能给我们一个你正在使用的编辑器配置的例子吗？ 您还提到了控制台错误，能否将它们包含在您的错误报告中？

```
<template>
	<div class="v-post-edit">
		<editor />
	</div>
</template>
<script>
/* tinymce 编辑器 */
import "tinymce/tinymce";
import editor from "@tinymce/tinymce-vue";
// icons
import "tinymce/icons/default";
// Theme
import "tinymce/themes/silver/theme";

// Skins
import "tinymce/skins/ui/oxide/skin.min.css";
import "tinymce/skins/ui/oxide/content.min.css";
import "tinymce/skins/content/default/content.min.css";

// Plugins
//import "tinymce/plugins/fullscreen";
//import "tinymce/plugins/paste";
//import "tinymce/plugins/autoresize";

/* tinymce 编辑器结束 */
export default {
	name: "v-post-edit",
	components: {
		editor,
	},
};
</script>
```
这是我完整的代码，它是可以正常工作的，但是控制台报错：
```
tinymce.js?e562:1799 GET http://localhost:208/js/skins/ui/oxide/skin.min.css net::ERR_ABORTED 404 (Not Found)
tinymce.js?e562:1799 GET http://localhost:208/js/skins/content/default/content.css net::ERR_ABORTED 404 (Not Found)
tinymce.js?e562:1799 GET http://localhost:208/js/skins/ui/oxide/content.min.css net::ERR_ABORTED 404 (Not Found)
```

**Comment by tiny-james** [comment]
It looks like you are bundling tinymce using webpack (or something similar). This is actually the hardest way to deploy TinyMCE.

Here is an example using standard TinyMCE:
https://github.com/tinymce/tinymce-webpack-example

You should be able to adapt that to Vue fairly easily.

There are 2 alternatives to bundling that I recommend instead of bundling if you want to self-host:

1. Download the self-hosted package ( https://www.tiny.cloud/get-tiny/downloads/ ) and host it relative to your app in a public folder. Then link to the `tinymce.min.js` file using `tinymce-script-src` ( https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src ).
2. Setup Webpack to copy the files from the `node_modules` folder into a public folder (like you would with the self-hosted package). Then link to the `tinymce.min.js` file using `tinymce-script-src` ( https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src ).

Of course you can also load directly from the cloud ( https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/ ).

------------

看起来您正在使用 webpack（或类似的东西）捆绑 tinymce。这实际上是部署 TinyMCE 最难的方式。

这是使用标准 TinyMCE 的示例：
https://github.com/tinymce/tinymce-webpack-example

你应该能够很容易地将它适应 Vue。

如果您想自托管，我建议有 2 种捆绑替代方案，而不是捆绑：

1. 下载自托管包 ( https://www.tiny.cloud/get-tiny/downloads/ ) 并将其相对于您的应用程序托管在公共文件夹中。然后使用`tinymce-script-src`（https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src）链接到`tinymce.min.js`文件。
2. 设置 Webpack 以将文件从 `node_modules` 文件夹复制到公共文件夹中（就像使用自托管包一样）。然后使用`tinymce-script-src`（https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src）链接到`tinymce.min.js`文件。

当然你也可以直接从云端加载（https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/）。

**Comment by mkinit** [comment]
> 看起来您正在使用 webpack（或类似的东西）捆绑 tinymce。这实际上是部署 TinyMCE 最难的方式。
> 
> 这是使用标准 TinyMCE 的示例：[https](https://github.com/tinymce/tinymce-webpack-example) :
> [//github.com/tinymce/tinymce-webpack-example](https://github.com/tinymce/tinymce-webpack-example)
> 
> 你应该能够很容易地将它适应 Vue。
> 
> 如果您想自托管，我建议有 2 种捆绑替代方案，而不是捆绑：
> 
> 1. 下载自托管包 ( https://www.tiny.cloud/get-tiny/downloads/ ) 并将其相对于您的应用程序托管在公共文件夹中。然后`tinymce.min.js`使用`tinymce-script-src`（https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src）链接到文件。
> 2. 设置 Webpack 以将文件从`node_modules`文件夹复制到公共文件夹（就像使用自托管包一样）。然后`tinymce.min.js`使用`tinymce-script-src`（https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src）链接到文件。
> 
> 当然你也可以直接从云端加载（https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/）。
> 
> 您的外表正在使用 webpack（或类似的东西）捆绑小 MCE。这实际上是 TinyMCE 最难的方式。
> 
> 这是使用标准 TinyMCE 的示例：
> https://github.com/tinymce/tinymce-webpack-example
> 
> 你应该能够很容易地将它适应 Vue。
> 
> 如果你想自首，我建议有两种选择捆绑方案，而不是捆绑：
> 
> 1. 下载自托管包（https://www.tiny.cloud/get-tiny/downloads/）并将其相对于您的应用程序托管在公共文件夹中。然后使用`tinymce-script-src`（[https://www.tiny.cloud /docs/integrations/vue/#tinymce-script-src）链接到`tinymce.min.js`文件。](https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src%EF%BC%89%E9%93%BE%E6%8E%A5%E5%88%B0%60tinymce.min.js%60%E6%96%87%E4%BB%B6%E3%80%82)
> 2. 设置 Webpack 以文件从`node_modules`文件夹复制到文件夹中（就像使用自给公共包一样）。然后使用`tinymce-script-src`（[https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src）链接到`tinymce.min.js`文件。](https://www.tiny.cloud/docs/integrations/vue/#tinymce-script-src%EF%BC%89%E9%93%BE%E6%8E%A5%E5%88%B0%60tinymce.min.js%60%E6%96%87%E4%BB%B6%E3%80%82)
> 
> 你当然也可以直接从云端加载（[https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/）。](https://www.tiny.cloud/docs/cloud-deployment-guide/editor-and-features/%EF%BC%89%E3%80%82)

已经可以正常使用并且不会报错了，非常感谢。
