### ISSUE TITLE
как интергировать этот редактор в nuxt 2 / how to integrate this editor in nuxt 2

### ISSUE THREAD

**Issue by coaperator** [tinymce/tinymce-vue#300]
сабж.
установил "@tinymce/tinymce-vue@^3" - для vue 2
но эта обертка TinyCloud загружает TinyCloud, заставить ее использовать self-hosted версию?
нормальная, человеческая инструкция есть?

пс: пытаюсь все это поставить в nuxt 2

-------------------

set "@tinymce/tinymce-vue@^3" - for vue 2
but this TinyCloud wrapper loads TinyCloud, make it use the self-hosted version?
Is there a normal, human instruction?

ps: I'm trying to put all this in nuxt 2

**Comment by jscasca** [comment]
@coaperator there are two ways for you to use a self-hosted version: 
1) You can load the TinyMCE script in your `index.html` file so that the global is available when your component loads.
2) You can make your self-hosted version publicly available and point to it using the `tinymceScriptSrc` property of the component. [Docs example](https://www.tiny.cloud/docs/integrations/vue/#exampleusingtinymce-script-src)
Let me know if this helps
