### ISSUE TITLE
package-lock.json file should not be in repo

### ISSUE THREAD

**Issue by aamirsaggi** [tinymce/tinymce-vue#56]
Hi,
I am facing issue with mem library, after checking package.json I found no mem but it is in package-lock.json that is creating issue from SourceClear.

It is always recommended to not push package-lock.json files on github because these -lock files are auto generated on machine when we run npm install.

Owner can you please remove package-lock.json so that many of the issue will be auto resolved.

**Comment by aamirsaggi** [comment]
Used mem 1.1.0 in this package that has some security issues.
Upgrade mem to version 4.0.0 or higher.
Please check this url.
https://snyk.io/vuln/npm:mem:20180117
Thanks

**Comment by SimonFc** [comment]
It's [`@storybook/storybook-deployer`](https://github.com/storybooks/storybook-deployer/blob/master/package.json#L30) that need to bump its version of `yargs` in order to resolve that dependency chain. The storybooks are only published to GitHub as well and not with tinymce-vue though so it's not a security issue here.

I'll be closing this issue but thanks for reporting it though!

**Comment by SimonFc** [comment]
I found an open issue for this: [Issue](https://github.com/storybooks/storybook-deployer/issues/54)
