### ISSUE TITLE
custom dialog  plugin demoi needed

### ISSUE THREAD

**Issue by hightechguy** [tinymce/tinymce-vue#65]
Hi,

I want to create a custom dialog  plugin with a complex logic (conditional controls, back end lookups etc)
Any example of Vuetifying 
https://www.tiny.cloud/docs/advanced/creating-a-plugin/ ?

Ideally it should be a separate Vue component. Is that possible?
Thanks!

**Comment by SimonFc** [comment]
I'm not sure if I understand, creating a plugin for TinyMCE got nothing to do with the tinymce-vue wrapper?

**Comment by shaunc869** [comment]
I think the question is how do we get to the tinymce object within the vue wrapper so we can do things like add a custom plugin, I have the same question. Thanks!

**Comment by SimonFc** [comment]
If you're hosting TinyMCE by yourself you have access to the object after the tinymce script has been loaded, so like this for example
```
import 'tinymce/tinymce';
import 'tinymce/themes/silver';

tinymce.PluginManager.add('customPlugin', (editor) => {
  // Do stuff here
});
```

It'll then be possible to use the plugin in your editor(s)
```
<editor plugins="customPlugin"></editor>
```

Actually loading through cloud highlights an issue here - you don't have access to the global tinymce object before an editor instance has been set up since the editor setup lazy loads the tinymce script. I'll look into if we can do some improvements here. Until then it's possible for cloud users to manually load their script like [this](https://www.tiny.cloud/docs/quick-start/)
```<script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=your_API_key"></script>``` before the tinymce-react component is used if access to the tinymce object is needed.

We're going to do some updates to the Docs in the near future, I'll make sure that we include something about this!

**Comment by shaunc869** [comment]
Actually since this is the vue wrapper in this content I realized that the vue wrapper puts tinyMCE into the window context so you can access it like this:

`window.tinyMCE.PluginManager.add('charactercount', function (editor) {}`

So what I did in this case is put the plugin code in the setup method of the editor like this:

```
setup: function (editor: any) {

					window.tinyMCE.PluginManager.add('charactercount', function (editor) {
plugin code here
}
```

this worked great in my use case.

**Comment by abuoop** [comment]
Its not appearing my button in toolbar
```
setup: function(editor){
        tinymce.PluginManager.add('example', function(editor) {
          var openDialog = function () {
            return editor.windowManager.open({
              title: 'Example plugin',
              body: {
                type: 'panel',
                items: [
                  {
                    type: 'input',
                    name: 'title',
                    label: 'Title'
                  }
                ]
              },
              buttons: [
                {
                  type: 'cancel',
                  text: 'Close'
                },
                {
                  type: 'submit',
                  text: 'Save',
                  primary: true
                }
              ],
              onSubmit: function (api) {
                var data = api.getData();
                // Insert content when the window form is submitted
                editor.insertContent('Title: ' + data.title);
                api.close();
              }
            });
          };
          
          // Add a button that opens a window
          editor.ui.registry.addButton('example', {
            text: 'My button',
            onAction: function () {
              // Open window
              openDialog();
            }
          });
        
          // Adds a menu item, which can then be included in any menu via the menu/menubar configuration
          editor.ui.registry.addMenuItem('example', {
            text: 'Example plugin',
            onAction: function() {
              // Open window
              openDialog();
            }
          });
        
          return {
            getMetadata: function () {
              return  {
                name: "Example plugin",
                url: "                              "
              };
            }
          };
        });
        window.tinymce.PluginManager.requireLangPack('example', 'sv_SE,de_AT');
    }
```
and not working till i put it into ``` export default { // }```
also not working. and error inside console is ``` Uncaught SyntaxError: Unexpected token < ```
