### ISSUE TITLE
Detailed explanation about the Self Hosted TinyMCE for Vue?

### ISSUE THREAD

**Issue by prashant1k99** [tinymce/tinymce-vue#73]
Please provide a detailed explanation on how to use the self hosted version of tinymce-vue?

**Comment by SimonFc** [comment]
Do you mean a more detailed explanation on how to make TinyMCE available in the global scope after the tinymce-vue wrapper has been set up? (So that it wouldn't load the cloud version of TinyMCE).

We're aware that some parts of the documentation for the tinymce-wrappers(React/Angular/Vue) could be even clearer so let me know what you're looking for to do and I'll see if we can include that.

**Comment by prashant1k99** [comment]
> Do you mean a more detailed explanation on how to make TinyMCE available in the global scope after the tinymce-vue wrapper has been set up? (So that it wouldn't load the cloud version of TinyMCE).
> 
> We're aware that some parts of the documentation of the tinymce-wrappers(React/Angular/Vue) could be even clearer so let me know what you're looking for and I'll see if we can include that.

Like the documentation for the Cloud Hosted one is given,... There should be a detailed explanation of how to use the Vue wrapper package Officially provided to work as Self Hosted....

**Comment by gadget-iom** [comment]
> Please provide a detailed explanation on how to use the self hosted version of tinymce-vue?

I couldn't get tinymce-vue setup in a self-hosted configuration either. 
Switched to CKEditor-vue instead. Works perfectly.

**Comment by Afraithe** [comment]
Self-hosted gets a bit tricky due to loading various resources on demand, so you need to make sure the skins follow through with the packaging you do. There are also multiple ways of setting it up so even if we write some docs around this, it's not likely to exactly match your scenario. Cloud is definitely a lot easier, it just works out of the box. But we are looking into improving the docs (getting it up to date for TinyMCE 5 first, I noticed some outdated info).

**Comment by Pyronerd62** [comment]
Here's the way we found 
https://github.com/tinymce/tinymce-vue/issues/30#issuecomment-461616029
For anyone struggling with this the documentation isn't helpful at all. This is how I resolved the issue.
First Import tinymce and copy the skins folder.
```
npm install tinymce --save
cp -r node_modules/tinymce/skins skins
```
To be safe I manually moved the skins folder to my public folder and then added this to my main.js
```
import "tinymce/tinymce"
import "tinymce/themes/silver" 
import "../public/skins/ui/oxide/skin.min.css"
import "../public/skins/ui/oxide/content.min.css"
import "../public/skins/content/default/content.min.css"
```
Then you can use the editor in any component you want.

**Comment by birdy90** [comment]
I still has some troubles, that I can't solve. 

Trying to create vue single file component with this template:

```
<template lang='pug'>
    div
        Editor(:id='`editor-${field.alias}`' :init='editorSettings' v-model='value')

</template>
```

and the script is...

```
<script>
  const tinymce = require('tinymce/tinymce');
  window.tinymce = tinymce;
  require('tinymce/themes/silver/theme');

  const Editor = require('@tinymce/tinymce-vue').default;

  module.exports = {
    name: 'RichTextEditor',
    props: ['field', 'value'],
    data() {
      return {
        editorSettings: {
          menubar: false,
          statusbar: false,
          skin: false,
          plugins: ['paste link image lists code'],
          language: 'ru',
          height: 640,
          toolbar: 'undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link image | code',
          language_url: '/static/files/main/tiny.mce.ru.js',

          images_upload_url: '/admin/file/upload',
          relative_urls: false,
          file_picker_types: 'image',

          image_dimensions: false,
          image_description: false,
        }
      }
    },
    ...
    components: {
      Editor,
    },
  }
</script>
```

But with sonfig I'm getting error `Failed to initialize the editor as the document is not in standards mode. TinyMCE requires standards mode.` and editor is not initialized.

In documentation I found that if I'm using `require`, then I have to write `deafult` like this:

```
  const tinymce = require('tinymce/tinymce').default;
  window.tinymce = tinymce;
  require('tinymce/themes/silver/theme');

  const Editor = require('@tinymce/tinymce-vue').default;
```

But in this case I'm getting `Uncaught TypeError: Cannot read property 'util' of undefined`. And if I remove `require('tinymce/themes/silver/theme');` then it is initialized, but hidden and I still have a message about loading from cloud (but it' not styled). Maybe someone can help me with what I'm doing wrong

**Comment by angelicochris** [comment]
This is still an issue. I've been racking my brain trying to figure out how to do this and still can't get it to work. The main issue is the skins. As I've seen else where include the skins in some places just seem to apply them globally instead of to the component and the component itself seems to not get any styles.
![image](https://user-images.githubusercontent.com/55987158/158384889-ea3f3184-845a-40cb-a7b9-607e24c921d1.png)
A simple example of a self hosted version would go a long way.

**Comment by aztral** [comment]
> > Please provide a detailed explanation on how to use the self hosted version of tinymce-vue?
> 
> I couldn't get tinymce-vue setup in a self-hosted configuration either. Switched to CKEditor-vue instead. Works perfectly.

I had the same problem. Thx for mentioning CKEditor as an alternative to the poor/non existent/fake even? documentation of a self hoisted vue app with TinyMCE. CKEditor works just as great for my needs and is a lot easier to set up. Just sit back, zip some coffee and follow the documentation on the CKEditor website. Took me 10-15 minutes to get running. Deeeeeceeent..! (Insert thumbs up emoji)
