### ISSUE TITLE
How to limit the length of the tinymce of input characters?

### ISSUE THREAD

**Issue by race616** [tinymce/tinymce-vue#75]
How to limit the length of the tinymce of input characters?

**Comment by SimonFc** [comment]
There's no native way in TinyMCE to put a limit on the number of characters contained in the editable area although it shouldn't be too difficult to implement the behavior. I found a question on [stack overflow](https://stackoverflow.com/questions/11342921/limit-the-number-of-character-in-tinymce) about the same thing and one of the answers give an example of an implementation. It's for an older version of Tiny 4 but should work the same with latest Tiny 4 & 5 as well.

I'll be closing this since it's not related to the tinymce-vue wrapper but a question about tinymce itself.
