### ISSUE TITLE
Drag and drop images into body like demo

### ISSUE THREAD

**Issue by shaunc869** [tinymce/tinymce-vue#76]
I apologize if this is a silly question, but if you look at the demo:

https://www.tiny.cloud/docs/demo/full-featured/

You can drag and drop an image into the body of the editor, how do we achieve this with the vue version? Thank you!

**Comment by SimonFc** [comment]
Not a silly question at all!
In that specific demo it's achieved by the [PowerPaste](https://www.tiny.cloud/docs/plugins/powerpaste/) plugin. It is a premium plugin although if you're only after the drag and drop functionality you can achieve that with the open source [Paste](https://www.tiny.cloud/docs/plugins/paste/) plugin as well. Simply add the paste plugin to your "plugins" property and add `paste_data_images: true` to your init configuration.

I'll close this issue since this should solve it but let me know if you encounter any problems!
