### ISSUE TITLE
Specify Version

### ISSUE THREAD

**Issue by TheJuki** [tinymce/tinymce-vue#9]
I need to support Internet Explorer 10. How do I specify that I need the 4.5.X branch version?

**Comment by TheJuki** [comment]
Nevermind. You just set cloud-channel='4.5'.

**Comment by TheJuki** [comment]
Well, it does work but I do get a VALIDATION ERROR! in the console.

**Comment by fyrkant** [comment]
Or more correctly, there is a 4.5 release on cloud but it's not the latest one, the 4.5 branch is a legacy branch that you will have to host yourself to get the latest version. But anyway, I'll remove the validation for the cloud channel because you can use it with the later releases also, but I don't recommend using the 4.5 channel.
